7012389 Modify svc:/system/install/config to satisfy needs of 'unconfiguration' 7005387 svc:/milestone/single-user:default should depend upon svc:/system/install/config

diff --git a/usr/src/cmd/system-config/svc/svc-system-config b/usr/src/cmd/system-config/svc/svc-system-config
--- a/usr/src/cmd/system-config/svc/svc-system-config
+++ b/usr/src/cmd/system-config/svc/svc-system-config
@@ -28,7 +28,7 @@
 #
 # Establish PATH for non-built in commands
 #
-export PATH=/usr/bin:/usr/sbin
+export PATH=/sbin:/usr/bin:/usr/sbin
 
 # load builtin commands
 builtin chmod
@@ -38,8 +38,35 @@ builtin grep
 builtin rm
 builtin rmdir
 
+TMP_DIR=/system/volatile
+
 ETC_SHADOW=/etc/shadow
-TMP_SHADOW=/tmp/shadow.$$
+TMP_SHADOW="${TMP_DIR}/shadow.$$"
+
+ETC_SUDOERS=/etc/sudoers
+TMP_SUDOERS="${TMP_DIR}/sudoers.$$"
+
+ETC_AUTO_HOME=/etc/auto_home
+TMP_AUTO_HOME="${TMP_DIR}/auto_home.$$"
+
+ETC_USER_ATTR=/etc/user_attr
+
+ETC_SUDOERS=/etc/sudoers
+TMP_SUDOERS="${TMP_DIR}/sudoers.$$"
+
+ETC_AUTO_HOME=/etc/auto_home
+TMP_AUTO_HOME="${TMP_DIR}/auto_home.$$"
+
+ETC_USER_ATTR=/etc/user_attr
+
+# path to SC profile generated by System Configuration Interactive (SCI) tool
+SCIT_SC_PROFILE="${TMP_DIR}/sc_profile.xml"
+
+# smf profile directory
+SMF_PROFILE_DIR=/etc/svc/profile
+
+# target destination for SC profile generated by SCI tool
+SC_PROFILE_DST=${SMF_PROFILE_DIR}/sc_profile.xml
 
 ETC_SUDOERS=/etc/sudoers
 TMP_SUDOERS=/tmp/sudoers.$$
@@ -50,11 +77,12 @@ TMP_AUTO_HOME=/tmp/auto_home.$$
 ETC_USER_ATTR=/etc/user_attr
 
 # site profile
-SITE_PROFILE=/etc/svc/profile/site.xml
+SITE_PROFILE=${SMF_PROFILE_DIR}/site.xml
 
 # property group definitions
 PG_USER_ACCOUNT="user_account"
 PG_ROOT_ACCOUNT="root_account"
+PG_CONFIGURATION="configuration"
 
 # directory containing initial user profile files
 ETC_SKEL=/etc/skel
@@ -63,6 +91,14 @@ DOT_PROFILE=".profile"
 DOT_BASHRC=".bashrc"
 INITIAL_DOT_PROFILE="$ETC_SKEL/$DOT_PROFILE"
 INITIAL_DOT_BASHRC="$ETC_SKEL/$DOT_BASHRC"
+
+# configuration properties
+# enable system configuration
+PROP_CONFIGURE="$PG_CONFIGURATION/configure"
+
+# bring up System Configuration Interactive tool
+PROP_INTERACTIVE_CONFIG="$PG_CONFIGURATION/interactive_config"
+
 
 # user account properties
 # login name
@@ -178,6 +214,49 @@ get_smf_prop()
 
 	print -u1 "$prop_value"
 	return 0
+}
+
+#
+# set_smf_prop()
+#
+# Description:
+#     Set value of SMF property.
+#
+# Parameters:
+#     $1 - SMF service
+#     $1 - property name
+#     $1 - property value
+#
+# Returns:
+#     Aborts with SMF_EXIT_ERR_FATAL in case of failure
+#
+set_smf_prop()
+{
+	typeset svc_name="$1"
+	typeset prop_name="$2"
+	typeset prop_value="$3"
+
+	svccfg -s $svc_name setprop $prop_name = $prop_value
+
+	if (( $? != 0 )) ; then
+		print -u2 "svccfg(1M) failed to set <$prop_name> property" \
+		    "to <$prop_value> for <$svc_name> smf service, aborting."
+
+		exit $SMF_EXIT_ERR_FATAL
+	fi
+
+	#
+	# Refresh service, so that configuration is propagated to running smf
+	# snapshot.
+	#
+	svcadm refresh $svc_name
+
+	if (( $? != 0 )) ; then
+		print -u2 "svcadm(1M) failed to refresh" \
+                    "<$svc_name> smf service, aborting."
+
+		exit $SMF_EXIT_ERR_FATAL
+	fi
 }
 
 #
@@ -366,7 +445,7 @@ create_initial_user_profile()
 		chmod 0644 "$home_dir/$DOT_BASHRC"
 		if (( $? != 0 )) ; then
 			print -u2 "Failed to change permissions to 0644" \
-			    "for ${home_dir}/$DOT_BASRC, aborting."
+			    "for ${home_dir}/$DOT_BASHRC, aborting."
 
 			exit $SMF_EXIT_ERR_FATAL
 		fi
@@ -882,9 +961,186 @@ remove_pg()
 		print -u2 "Failed to remove <$pg> property group, aborting."
 		exit $SMF_EXIT_ERR_FATAL
 	fi
+
+	# refresh service, so that change is reflected in running smf snapshot
+	svcadm refresh $SMF_FMRI
+
+	if (( $? != 0 )) ; then
+		print -u2 "svcadm(1M) failed to refresh" \
+                    "$SMF_FMRI smf service, aborting."
+
+		exit $SMF_EXIT_ERR_FATAL
+	fi
 }
 
+#
+# set_terminal_type()
+#
+# Description:
+#     If TERM variable is not defined, set it to:
+#      * "sun" if connected to SPARC via keyboard/monitor,
+#      * "sun-color" if connected to X86 via keyboard/monitor,
+#      * "vt100" otherwise.
+#
+set_terminal_type()
+{
+	[[ -n "$TERM" ]] && return
+
+	# start with vt100 as a default value
+	TERM=vt100
+
+	arch=$(uname -p)
+	if [[ "$arch" == "sparc" ]] ; then
+		output_device=$(eeprom output-device | cut -f 2 -d '=')
+
+		[[ -n "$output_device" ]] &&
+		    print -u1 " output-device property is set to" \
+		        "$output_device." ||
+		    print -u1 " output-device property is not configured."
+
+		[[ "$output_device" == "screen" ]] && TERM="sun"
+	else
+		cons=$(devprop console)
+		if (( $? == 0 )) ; then
+			if [[ $cons =~ ^tty ]] ; then
+				print -u1 " Console redirected to serial port" \
+				    "$cons."
+			else
+				TERM="sun-color"
+			fi
+		else
+		    print -u1 " Could not obtain value of console property."
+		fi
+	fi
+
+	print -u1 " Setting terminal type to $TERM."
+
+	export TERM
+}
+
+#
+# run_sci_tool()
+#
+# Description:
+#     Invokes System Configuration Interactive tool.
+#     Aborts with SMF_EXIT_ERR_FATAL in case of fatal failure.
+#
+run_sci_tool()
+{
+	print -u1 " Interactive configuration requested," \
+	    "bringing up System Configuration Interactive tool."
+
+	if [[ ! -x "/usr/bin/sysconfig" ]] ; then
+		print -u1 " SCI tool not found," \
+		    "skipping interactive configuration."
+
+		return
+	fi
+
+	#
+	# First make sure terminal type is configured. That's required by curses
+	# module which SCI tool consumes.
+	#
+	set_terminal_type
+
+	#
+	# dladm(1m) consumed by SCI tool relies on populated device tree.
+	# We should let system/device/local take care of that during first
+	# post-install boot of global zone (device tree is pre-populated in
+	# non-global zones).
+	# But at this point we can't depend on system/device/local due to
+	# CR7011249. So as a stop-gap solution, we explicitly call devfsadm(1m).
+	# to populate device tree. Once that bug is fixed, remove this code and
+	# uncomment related portion of system/config manifest.
+	#
+	if smf_is_globalzone; then
+		print -u1 " Invoking devfsadm(1m) to populate device tree."
+
+		devfsadm
+
+		if (( $? != 0 )) ; then
+			print -u2 "devfsadm(1m) failed, aborting."
+			exit $SMF_EXIT_ERR_FATAL
+		fi
+	fi
+
+	SC_FILE=$SCIT_SC_PROFILE sysconfig < /dev/console > /dev/console 2>&1
+	typeset -i ret=$?
+
+	# if SCI tool failed to create SC profile, abort
+	if [[ $ret != 0 ]] ; then
+		print -u2 -f "%s%d%s\n" \
+		    "SCI tool failed to create SC profile, (ret=" \
+		    $ret \
+		    ", aborting."
+
+		exit $SMF_EXIT_ERR_FATAL
+	fi
+
+	#
+	# If SCI tool didn't generate SC profile (for instance when user
+	# prematurely quit the application), return.
+	#
+	if [[ ! -r $SCIT_SC_PROFILE ]] ; then
+		print -u1 " SCI tool did not create SC profile," \
+		    "skipping the rest of interactive configuration."
+
+		return
+	fi
+
+	# move created SC profile to the directory dedicated for smf profiles
+	mv $SCIT_SC_PROFILE $SC_PROFILE_DST
+
+	if (( $? != 0 )) ; then
+		print -u2 "Failed to move $SCIT_SC_PROFILE" \
+                    "to $SC_PROFILE_DST, aborting."
+
+		exit $SMF_EXIT_ERR_FATAL
+	fi
+}
+
+
 ## Main ##
+
+# Check if system configuration should be carried out
+enable_configuration=$(get_smf_prop $PROP_CONFIGURE)
+if [[ "$enable_configuration" == "true" ]]; then
+
+	#
+	# Check if System Configuration Interactive tool should be invoked to
+	# carry out interactive system configuration.
+	#
+	interactive_config=$(get_smf_prop $PROP_INTERACTIVE_CONFIG)
+	if [[ "$interactive_config" == "true" ]]; then
+		run_sci_tool
+
+		#
+		# Interactive configuration succeeded, reset interactive_config
+		# property.
+		#
+		set_smf_prop $SMF_FMRI $PROP_INTERACTIVE_CONFIG false
+	fi
+
+	# If exists, apply System Configuration profile.
+	if [[ -r $SC_PROFILE_DST ]] ; then
+		print -u1 " Applying $SC_PROFILE_DST SC profile."
+
+		svccfg apply $SC_PROFILE_DST
+
+		if (( $? != 0 )) ; then
+			print -u2 "svccfg(1M) failed to apply" \
+        	            "$SC_PROFILE_DST, aborting."
+
+			exit $SMF_EXIT_ERR_FATAL
+		fi
+	else
+		print -u1 " $SC_PROFILE_DST does not exist," \
+		    "skipping step of applying System Configuration profile."
+	fi
+
+	# System configuration succeeded, reset configure property.
+	set_smf_prop $SMF_FMRI $PROP_CONFIGURE false
+fi
 
 # check if root account is to be configured
 svcprop -C -q -p $PG_ROOT_ACCOUNT $SMF_FMRI
@@ -894,7 +1150,7 @@ svcprop -C -q -p $PG_ROOT_ACCOUNT $SMF_FMRI
 svcprop -C -q -p $PG_USER_ACCOUNT $SMF_FMRI
 (( $? == 0 )) && configure_user=true || configure_user=false
 
-# configure root acount
+# configure root account
 if $configure_root; then
 	print -u1 "Configuring root account."
 
@@ -905,7 +1161,7 @@ if $configure_root; then
 	print -u1 "root account successfully configured."
 fi
 
-# configure user acount
+# configure user account
 if $configure_user; then
 	print -u1 "Configuring user account."
 
