3977 /lib/svc/method/auto-installer exits with $SMF_EXIT_OK even if AI engine fails

diff --git a/usr/src/cmd/auto-install/svc/auto-installer b/usr/src/cmd/auto-install/svc/auto-installer
--- a/usr/src/cmd/auto-install/svc/auto-installer
+++ b/usr/src/cmd/auto-install/svc/auto-installer
@@ -135,10 +135,11 @@ if [ ! -x  $AI_ENGINE ] ; then
 fi
 
 $AI_ENGINE -p $AISC_MANIFEST
-ret = $?
+ret=$?
 
-if [ ret -ne 0 ] ; then
-	echo "Automated Installation failed - error " $ret
+if [ $ret -ne 0 ] ; then
+	echo "Automated Installation failed - error $ret" > /dev/msglog
+	echo "Automated Installation failed - error $ret"
 	exit $SMF_EXIT_ERR_FATAL
 fi
 
