Fixes bugs 532 and 838. It also fixes license errors and updates

diff --git a/usr/src/cmd/slim-install/svc/live-fs-root b/usr/src/cmd/slim-install/svc/live-fs-root
--- a/usr/src/cmd/slim-install/svc/live-fs-root
+++ b/usr/src/cmd/slim-install/svc/live-fs-root
@@ -3,9 +3,8 @@
 # CDDL HEADER START
 #
 # The contents of this file are subject to the terms of the
-# Common Development and Distribution License, Version 1.0 only
-# (the "License").  You may not use this file except in compliance
-# with the License.
+# Common Development and Distribution License (the "License").
+# You may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 # or http://www.opensolaris.org/os/licensing.
@@ -207,55 +206,35 @@ then
 		exit $SMF_EXIT_ERR_FATAL
 	fi
 
-	/usr/sbin/lofiadm -a /.cdrom/solaris.zlib &
-	lofipid="$!"
-	
-	cnt=0
-	while [ $cnt -lt 2 ]
-	do
-		/usr/bin/sleep 1
-		/usr/sbin/devfsadm -i lofi 2> /dev/msglog
-		if [ -b /devices/pseudo/lofi@0:1 ]
-		then
-			cnt=2
-		else
-			cnt=`expr $cnt + 1`
-		fi
+	# Explictly create lofi devices for solaris.zlib and 
+	# solarismisc.zlib
 
-		if [ ! -b /devices/pseudo/lofi@0:1 ]
-		then
-			[ $cnt -eq 2 ] && echo "** Loopback device not created! **" > /dev/msglog
-			continue
-		fi
-		
-		wait $lofipid
-		LOFI_MISC_DEV=`/usr/sbin/lofiadm -a /.cdrom/solarismisc.zlib`
-		
-		/sbin/mount -F hsfs -o ro /dev/lofi/1 /usr
-		if [ $? -ne 0 ]
-		then
-			echo "/usr MOUNT FAILED!"
-			break
-		fi
-
-		
-		/sbin/mount -F hsfs -o ro $LOFI_MISC_DEV /mnt/misc
-		if [ $? -ne 0 ]
-		then
-			echo "/mnt/misc MOUNT FAILED!"
-			break
-		fi
-
-		MOUNTED=1
-		break
-	done
-	
-	if [ "$MOUNTED" != "1" ]
+	/usr/sbin/lofiadm -a /.cdrom/solaris.zlib /dev/lofi/1 || break
+	/sbin/mount -F hsfs -o ro /dev/lofi/1 /usr 
+	if [ $? -ne 0 ]
 	then
-		echo "** FATAL **: Unable to mount Live image!"
+		echo "/usr MOUNT FAILED!" 
 		exit $SMF_EXIT_ERR_FATAL
 	fi
+
+	/usr/sbin/lofiadm -a /.cdrom/solarismisc.zlib /dev/lofi/2 || break
+
+	/sbin/mount -F hsfs -o ro /dev/lofi/2 /mnt/misc
+
+	if [ $? -ne 0 ]
+	then
+		echo "/mnt/misc MOUNT FAILED!"
+		exit $SMF_EXIT_ERR_FATAL
+	fi
+
+	MOUNTED=1
 	echo "Done mounting Live image" > /dev/msglog
+fi
+
+if [ "$MOUNTED" -ne 1 ]
+then
+    echo "** FATAL **: Unable to mount Live image!" > /dev/msglog
+    exit $SMF_EXIT_ERR_FATAL
 fi
 
 #
