16400 exec_methods in distro constructor need to add the required parameter "timeout_seconds" 16408 install-incorporation missing entries for some renamed packages 16411 Fix for CR 6354954 causes mounting of solarismisc.zlib to hang

diff --git a/usr/src/cmd/slim-install/svc/media-fs-root b/usr/src/cmd/slim-install/svc/media-fs-root
--- a/usr/src/cmd/slim-install/svc/media-fs-root
+++ b/usr/src/cmd/slim-install/svc/media-fs-root
@@ -121,19 +121,31 @@ fi
 # because the mount command enforces nosetuid, and /usr
 # needs to have the setuid capability.
 #
-/usr/sbin/lofiadm -a /.cdrom/$SOLARIS_ZLIB /dev/lofi/1
-if [ $? -ne 0 ]; then
+#
+# Must use lofiadm in combination with the mount command,
+# as with the changes to make lofi work from within a zone,
+# a properly populated /dev tree is required to use simply
+# "mount" - this applies to both .zlib files.
+#
+usr_lofi_dev=$(/usr/sbin/lofiadm -a /.cdrom/$SOLARIS_ZLIB)
+if [ $? -ne 0 -o -z "$usr_lofi_dev" ]; then
 	echo "lofiadm of /usr FAILED!" 
 	exit $SMF_EXIT_ERR_FATAL
 fi
-$MOUNT -F hsfs -o ro /dev/lofi/1 /usr
+$MOUNT -F hsfs -o ro ${usr_lofi_dev} /usr
 if [ $? -ne 0 ]; then
 	echo "/usr MOUNT FAILED!" 
 	exit $SMF_EXIT_ERR_FATAL
 fi
 
 
-$MOUNT -F hsfs -o ro /.cdrom/$SOLARISMISC_ZLIB /mnt/misc
+misc_lofi_dev=$(/usr/sbin/lofiadm -a /.cdrom/$SOLARISMISC_ZLIB)
+if [ $? -ne 0 -o -z "$misc_lofi_dev" ]; then
+	echo "lofiadm of /mnt/misc FAILED!"
+	exit $SMF_EXIT_ERR_FATAL
+fi
+
+$MOUNT -F hsfs -o ro ${misc_lofi_dev} /mnt/misc
 if [ $? -ne 0 ]; then
 	echo "/mnt/misc MOUNT FAILED!"
 	exit $SMF_EXIT_ERR_FATAL
diff --git a/usr/src/cmd/slim-install/svc/net-fs-root b/usr/src/cmd/slim-install/svc/net-fs-root
--- a/usr/src/cmd/slim-install/svc/net-fs-root
+++ b/usr/src/cmd/slim-install/svc/net-fs-root
@@ -20,8 +20,7 @@
 # CDDL HEADER END
 #
 #
-# Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
-# Use is subject to license terms.
+# Copyright (c) 2009, 2010, Oracle and/or its affiliates. All rights reserved.
 #
 
 # Make sure that the libraries essential to this stage of booting can be found.
@@ -232,6 +231,13 @@ fi
 # because the mount command enforces nosetuid, and /usr
 # needs to have the setuid capability.
 #
+# Additionally:
+# Must use lofiadm in combination with the mount command,
+# as with the changes to make lofi work from within a zone,
+# a properly populated /dev tree is required to use simply
+# "mount" - this applies to both .zlib files.
+#
+
 usr_lofi_dev=`/usr/sbin/lofiadm -a /tmp/$SOLARIS_ZLIB`
 if [ $? -ne 0 -o -z "$usr_lofi_dev" ]
 then
@@ -246,12 +252,13 @@ then
 	exit $SMF_EXIT_ERR_FATAL
 fi
 
-#
-# As setting 'nosuid' is acceptable for /mnt/misc filesystem,
-# we can take advantage of mounting that file directly and
-# skipping explicit lofi mount step required for /usr
-#
-$MOUNT -F hsfs /tmp/$SOLARISMISC_ZLIB /mnt/misc
+misc_lofi_dev=$(usr/sbin/lofiadm -a /tmp/$SOLARISMISC_ZLIB)
+if [ $? -ne 0 -o -z "$misc_lofi_dev" ]; then
+	echo "Couldn't lofi mount /mnt/misc filesystem" > /dev/msglog
+	exit $SMF_EXIT_ERR_FATAL
+fi
+
+$MOUNT -F hsfs ${misc_lofi_dev} /mnt/misc
 if [ $? -ne 0 ]
 then
 	echo "Couldn't mount /mnt/misc" > /dev/msglog
