7004610 Update Text Installer to use CUD 7039676 TransferCPIO checkpoint sometimes won't calculate install size correctly 7043391 Wrong definition for VFSTAB_FILE variable in target controller
--HG--
rename : usr/src/cmd/text-install/osol_install/text_install/Makefile => usr/src/cmd/text-install/Makefile
rename : usr/src/cmd/text-install/osol_install/text_install/__init__.py => usr/src/cmd/text-install/__init__.py
rename : usr/src/cmd/text-install/osol_install/text_install/disk_selection.py => usr/src/cmd/text-install/disk_selection.py
rename : usr/src/cmd/text-install/osol_install/text_install/disk_window.py => usr/src/cmd/text-install/disk_window.py
rename : usr/src/cmd/text-install/osol_install/text_install/fdisk_partitions.py => usr/src/cmd/text-install/fdisk_partitions.py
rename : usr/src/cmd/text-install/osol_install/text_install/install_progress.py => usr/src/cmd/text-install/install_progress.py
rename : usr/src/cmd/text-install/osol_install/text_install/install_status.py => usr/src/cmd/text-install/install_status.py
rename : usr/src/cmd/text-install/osol_install/text_install/log_viewer.py => usr/src/cmd/text-install/log_viewer.py
rename : usr/src/cmd/text-install/osol_install/text_install/partition_edit_screen.py => usr/src/cmd/text-install/partition_edit_screen.py
rename : usr/src/cmd/text-install/osol_install/text_install/summary.py => usr/src/cmd/text-install/summary.py
rename : usr/src/cmd/text-install/osol_install/text_install/test/test_disk_select.py => usr/src/cmd/text-install/test/test_disk_select.py
rename : usr/src/cmd/text-install/osol_install/text_install/test/test_disk_window.py => usr/src/cmd/text-install/test/test_disk_window.py
rename : usr/src/cmd/text-install/osol_install/text_install/test/test_text_install.py => usr/src/cmd/text-install/test/test_text_install.py
rename : usr/src/cmd/text-install/osol_install/text_install/text-install => usr/src/cmd/text-install/text-install
rename : usr/src/cmd/text-install/osol_install/text_install/ti_install.py => usr/src/cmd/text-install/ti_install.py
rename : usr/src/cmd/text-install/osol_install/text_install/ti_install_utils.py => usr/src/cmd/text-install/ti_install_utils.py
rename : usr/src/cmd/text-install/osol_install/text_install/welcome.py => usr/src/cmd/text-install/welcome.py

diff --git a/usr/src/cmd/slim-install/svc/net-assembly b/usr/src/cmd/slim-install/svc/net-assembly
--- a/usr/src/cmd/slim-install/svc/net-assembly
+++ b/usr/src/cmd/slim-install/svc/net-assembly
@@ -60,10 +60,6 @@ WAITRETRY=10
 # Image Info file (needed for x86 AI, and both for Text Installs)
 IMAGE_INFO=".image_info"
 
-# Save folder information (needed for Text Installs)
-SAVE="save"
-SAVE_LIST="save_list"
-
 # Sparc installation configuration
 INSTALL_CONF_FILE="install.conf"
 INSTALL_CONF_SPEC="/tmp/$INSTALL_CONF_FILE"
@@ -251,11 +247,11 @@ fi
 for file in $SOLARIS_ZLIB $SOLARISMISC_ZLIB $IMAGE_INFO $config_file; do
 
 	print "Downloading $file" > /dev/msglog
-	$WGET --continue --tries=$TRIES --waitretry=$WAITRETRY \
-	    --timeout=$TIMEOUT ${url}/$file -O /tmp/$file >/dev/msglog 2>&1
+        $WGET --continue --tries=$TRIES --waitretry=$WAITRETRY \
+            --timeout=$TIMEOUT ${url}/$file -O /tmp/$file >/dev/msglog 2>&1
 
-	# if wget exits with failure, then exit 
-	if [ $? -ne 0 ]; then
+        # if wget exits with failure, then exit
+        if [ $? -ne 0 ]; then
 		print "Could not obtain $url/$file from install server" \
 		    > /dev/msglog
 		print "Please verify that the install server is correctly" \
@@ -337,29 +333,6 @@ fi
 #
 if [ "$TEXT_FLAG" == "true" ]; then
 	
-	# Retrieve the 'save' files (needed by remove_livecd_environment ICT)
-	cd /tmp
-	$WGET -x -i $url/$SAVE_LIST > /dev/msglog 2>&1
-	if [ "$?" != "0" ]; then
-		echo "ERROR: Failed to download save folder contents" > /dev/msglog
-		exit $SMF_EXIT_ERR_FATAL
-	fi
-	save_folder=$(print $url | $SED 's#.*//##')/$SAVE
-	cd -
-
-	# When net-booted, only the contents of /.cdrom/save
-	# (catalogued in the save_list)
-	# are relevant to the '.livecd-cdrom-content' file
-	$WGET $url/$SAVE_LIST -O /tmp/.livecd-cdrom-content
-	
-
-	# Link all of the downloaded files to where they should be in order to mimic CD
-	ln -s /tmp/solarismisc.zlib /.cdrom/solarismisc.zlib
-	ln -s /.volsetid /.cdrom/.volsetid 
-	ln -s /tmp/.image_info /.cdrom/.image_info
-	ln -s /tmp/.livecd-cdrom-content /.cdrom/.livecd-cdrom-content
-	ln -s /tmp/$save_folder /.cdrom/save
-
 	$SVCADM disable -s $CLI_LOGIN 
 	if [ "$?" != "0" ]; then
 		echo "svcadm failed to disable client login" > /dev/msglog
