3456 Distro-Constructor needs to support Automated Installer 3530 List of finalizer args in manifest aren't passed to finalizer scripts correctly
--HG--
rename : usr/src/cmd/distro_const/slim_cd/generic_live.xml => usr/src/cmd/distro_const/slim_cd/slimcd_generic_live.xml
rename : usr/src/cmd/distro_const/slim_cd/iso.sort => usr/src/cmd/distro_const/slim_cd/slimcd_iso.sort
rename : usr/src/cmd/distro_const/slim_cd/post_bootroot_pkg_image_mod => usr/src/cmd/distro_const/slim_cd/slimcd_post_bootroot_pkg_image_mod
rename : usr/src/cmd/distro_const/slim_cd/pre_bootroot_pkg_image_mod => usr/src/cmd/distro_const/slim_cd/slimcd_pre_bootroot_pkg_image_mod

diff --git a/usr/src/cmd/distro_const/utils/post_bootroot_pkg_image_mod b/usr/src/cmd/distro_const/utils/post_bootroot_pkg_image_mod
--- a/usr/src/cmd/distro_const/utils/post_bootroot_pkg_image_mod
+++ b/usr/src/cmd/distro_const/utils/post_bootroot_pkg_image_mod
@@ -23,21 +23,39 @@
 # Use is subject to license terms.
 #
 
+# =============================================================================
+# =============================================================================
+# post_bootroot_pkg_image_mod
+#
+# Customizations to the package image area after bootroot construction completes
+# =============================================================================
+# =============================================================================
 
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+create_ufs_fs()
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 #
 # Creates a UFS file system with the specified name and size, and mount it
 # on the specified mountpoint
 #
-#	arg1: name of the file to be used as the file system
-#	arg2: size of the file system to create in kilobyte
-#	arg3: mount point to mount this file system
+# Args:
+# 
+#  fname: name of the file to be used as the file system
 #
-create_ufs_fs()
+#  size: size of the file system to create in kilobyte
+#
+#  mntpt: mount point to mount this file system
+#
+# Returns:
+#  0 on success
+#  1 on error
+#
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 {
-
 	if [ "$#" -ne 3 ] ; then
-		echo "Calling create_ufs_fs() with the wrong number of arguments"
-		exit 1
+		print -u2 "$0: Calling create_ufs_fs() with the" \
+		    "wrong number of arguments"
+		return 1
 	fi
 	fname=$1
 	size=$2
@@ -46,77 +64,97 @@ create_ufs_fs()
 	# create the mount point
         [ -d ${mntpt} ] || mkdir -p ${mntpt}
 	if [ $? -ne 0 ] ; then
-		echo "FAILURE: Unable to mkdir ${mntpt}"
-		exit 1	
+		print -u2 "$0: FAILURE: Unable to mkdir ${mntpt}"
+		return 1	
 	fi
 
         rm -f ${fname}
         /usr/sbin/mkfile ${size}k ${fname}
 	if [ $? -ne 0 ] ; then
-		echo "FAILURE: Unable to create file ${fname} for ufs filesystem"
+		print -u2 "$0: FAILURE: Unable to create file ${fname}" \
+		    "for ufs filesystem"
 		/bin/rmdir ${mntpt}
-		exit 1
+		return 1
 	fi
 
         # loopback mount the boot archive
         lofidev=`/usr/sbin/lofiadm -a ${fname}`
         if [ $? -ne 0 ] ; then
-                echo "FAILURE: Unable to create loopback device for ${fname}"
+                print -u2 "$0: FAILURE: Unable to create loopback" \
+		    "device for ${fname}"
 		/bin/rm ${fname}
 		/bin/rmdir ${mntpt}
-		exit 1
+		return 1
         fi
 
 	# get the boot archive raw device and create a filesystem on it
         rlofidev=`echo $lofidev | sed s/lofi/rlofi/`
         /usr/sbin/newfs -m 0 $rlofidev < /dev/null 
         if [ $? -ne 0 ] ; then
-                echo "FAILURE: Unable to newfs $rlofidev"
+                print -u2 "$0: FAILURE: Unable to newfs $rlofidev"
 		/usr/sbin/lofiadm -d ${fname}
 		/bin/rm ${fname}
 		/bin/rmdir ${mntpt}
-		exit 1
+		return 1
         fi
 
 	# mount ufs filesystem on the specified mountpoint
         /usr/sbin/mount -o nologging $lofidev ${mntpt}
         if [ $? -ne 0 ] ; then
-                echo "FAILURE: Unable to mount $lofidev on $mntpt"
+                print -u2 "$0: FAILURE: Unable to mount $lofidev on $mntpt"
 		/usr/sbin/lofiadm -d ${fname}
 		/bin/rm ${fname}
 		/bin/rmdir ${mntpt}
-		exit 1
+		return 1
         fi
+
+	return 0
 }
 
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Main
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Customizations to the package image area after bootroot construction
+# completes.
+# 
+# Args:
+#   MFEST_SOCKET: Socket needed to get manifest data via ManifestRead object
 #
-# Begin the actual program
+#   PKG_IMG_PATH: Package image area
 #
+#   TMP_DIR: Temporary directory to contain the bootroot file
+# 
+# Note: This assumes a populated pkg_image area exists at the location
+#		${PKG_IMG_PATH} and that the bootroot has been built.
+#
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 if [ "$#" != "3" ] ; then
-	echo "Usage: $0 client_socket_name pkg_img_area_path tmp_dir_path"
+	print -u2 "Usage: $0: Requires 3 args:" \
+	    "Reader socket, pkg_image mntpt, tmp_dir"
 	exit 1
 fi
 
-SOCK_NAME=$1
+MFEST_SOCK=$1
 PKG_IMG_PATH=$2
 if [ ! -d ${PKG_IMG_PATH} ] ; then
-	echo "Image package area ${PKG_IMG_PATH} is not valid"
+	print -u2 "$0: Image package area ${PKG_IMG_PATH} is not valid"
 	exit 1
 fi
 
 TMP_DIR=$3
-if [ ! -d ${TMP_DIR} ] ; then
-	echo "$TMP_DIR is not valid"
+if [ ! -d $TMP_DIR ] ; then
+	print -u2 "$0: Temporary area $TMP_DIR is not valid"
 	exit 1
 fi
 
-COMPRESSION_TYPE=`/bin/ManifestRead ${SOCK_NAME} "img_params/live_img_compression/type"`
+COMPRESSION_TYPE=`/bin/ManifestRead ${MFEST_SOCK} "img_params/live_img_compression/type"`
 if [ "XX${COMPRESSION_TYPE}" = "XX" ] ; then
 	COMPRESSION_TYPE="gzip"
 fi
 
-DIST_ISO_SORT=/usr/share/distro_const/slim_cd/iso.sort
+# Note that DIST_ISO_SORT may or may not exist, given the type of image.
+DIST_ISO_SORT=`/bin/ManifestRead -k ${MFEST_SOCK} "iso_sort"`
 
 # Remove password lock file left around from user actions during
 # package installation; if left in place it becomes a symlink
@@ -124,17 +162,10 @@ DIST_ISO_SORT=/usr/share/distro_const/slim_cd/iso.sort
 # create a user account to fail
 /bin/rm ${PKG_IMG_PATH}/etc/.pwd.lock
 
-# Remove the icon theme caches
-echo "Cleaning out icon theme cache"
-if [ -d ${PKG_IMG_PATH}/usr ] ; then
-	cd ${PKG_IMG_PATH}/usr
-	/bin/find . -name icon-theme.cache -print|/bin/xargs rm
-fi
-
 # sbin, kernel and lib are all in the root archive
 cd ${PKG_IMG_PATH}
 if [ "$?" = "0" ] ; then
-	echo "Removing sbin, kernel and lib from package image area"
+	print -u2 "Removing sbin, kernel and lib from package image area"
 	/bin/rm -rf sbin kernel lib
 fi
 
@@ -165,50 +196,54 @@ title Boot from Hard Disk
 	chainloader +1
 ENDMENU
 
-echo "Generating usr filesystem image"
+print "Generating usr filesystem image"
 cd ${PKG_IMG_PATH}
 if [ "$?" != "0" ] ; then
-	echo "Unable to change directory to ${PKG_IMG_PATH}"
+	print -u2 "$0: Unable to change directory to ${PKG_IMG_PATH}"
 	exit 1
 fi
 
 if [[ "X${DIST_ISO_SORT}" != "X" && -s "${DIST_ISO_SORT}" ]]; then
 	SORT_OPTION="-sort ${DIST_ISO_SORT}"
+else
+	SORT_OPTION=""
 fi
+
 /bin/mkisofs -o solaris.zlib $SORT_OPTION -quiet -N -l -R \
     -U -allow-multidot -no-iso-translate -cache-inodes \
     -d -D -V "compress" usr
 
 if [ $? -ne 0 ] ; then
-	echo "FAILURE: mkisofs of solaris failed"
+	print -u2 "$0: FAILURE: mkisofs of solaris failed"
 	exit 1	
 fi
 
-echo "Confirm lofiadm is available."
+print "Confirm lofiadm is available."
 if [ ! -f ${PKG_IMG_PATH}/usr/sbin/lofiadm ] ; then
-	echo "FAILURE: ${PKG_IMG_PATH}/usr/sbin/lofiadm NOT FOUND"
+	print -u2 "$0: FAILURE: ${PKG_IMG_PATH}/usr/sbin/lofiadm NOT FOUND"
 	exit 1
 fi
 
 LOFI_OUT_STR=${TMP_DIR}/lofi_out_str.$$
 
-echo "Compressing usr filesystem image"
+print "Compressing usr filesystem image"
 LD_LIBRARY_PATH=${PKG_IMG_PATH}/usr/lib time ${PKG_IMG_PATH}/usr/sbin/lofiadm -C $COMPRESSION_TYPE ${PKG_IMG_PATH}/solaris.zlib >/dev/null 2>$LOFI_OUT_STR
 if [ $? -ne 0 ] ; then
 	/usr/bin/grep "invalid algorithm name" $LOFI_OUT_STR
 	if [ $? -eq 0 ] ; then
-		echo "$COMPRESSION_TYPE is an invalid lofiadm algorithm."
-		echo "Please modify your COMPRESSION_TYPE parameter."
+		print -u2 "$0: $COMPRESSION_TYPE is an invalid lofiadm" \
+		    "algorithm."
+		print -u2 "Please modify your COMPRESSION_TYPE parameter."
 		/bin/rm $LOFI_OUT_STR
 		exit 1
 	fi
 	/bin/rm $LOFI_OUT_STR
-	echo "FAILURE: compression of solaris failed"
+	print -u2 "$0: FAILURE: compression of solaris failed"
 	exit 1	
 fi
 /bin/rm $LOFI_OUT_STR
 
-echo "Generating pkg filesystem image"
+print "Generating pkg filesystem image"
 
 #
 # Back to the top of the package image area
@@ -216,7 +251,7 @@ echo "Generating pkg filesystem image"
 
 /bin/cd ${PKG_IMG_PATH}
 if [ "$?" != "0" ] ; then
-	echo "Unable to change directory to ${PKG_IMG_PATH}"
+	print -u2 "$0: Unable to change directory to ${PKG_IMG_PATH}"
 	exit 1
 fi
 #name of the archive containing the contents of IPS data
@@ -232,6 +267,10 @@ t=`du -sk var/pkg|cut -f1`
 pkgarchive_size=$(($t / 100 + $t))
 
 create_ufs_fs ${pkgarchive} ${pkgarchive_size} ${pkgarchive_mntpt}
+if [ "$?" == 1 ] ; then
+	print -u2 "$0: Error calling create_ufs_fs"
+	exit 1
+fi
 
 #copy the content of proto area's var/pkg to the pkg archive
 /bin/find var/pkg | /usr/bin/cpio -pdum ${pkgarchive_mntpt}
@@ -239,18 +278,18 @@ create_ufs_fs ${pkgarchive} ${pkgarchive_size} ${pkgarchive_mntpt}
 /usr/sbin/umount ${pkgarchive_mntpt}
 /usr/sbin/lofiadm -d ${pkgarchive}
 
-echo "Compressing pkg archive"
+print "Compressing pkg archive"
 LD_LIBRARY_PATH=${PKG_IMG_PATH}/usr/lib time ${PKG_IMG_PATH}/usr/sbin/lofiadm -C $COMPRESSION_TYPE $pkgarchive >/dev/null 2>&1
 if [ $? -ne 0 ] ; then
-	echo "FAILURE: compression of pkg archive failed"
-	fatal_exit	
+	print -u2 $0: "FAILURE: compression of pkg archive failed"
+	exit 1
 fi
 /bin/rm -rf ${PKG_IMG_PATH}/var/pkg/*
 
-echo "Generating misc filesystem image"
+print "Generating misc filesystem image"
 /bin/cd ${PKG_IMG_PATH}
 if [ "$?" != "0" ] ; then
-	echo "Unable to change directory to ${PKG_IMG_PATH}"
+	print -u2 "$0: Unable to change directory to ${PKG_IMG_PATH}"
 	exit 1
 fi
 mkdir miscdirs
@@ -261,15 +300,15 @@ mv var miscdirs
     -no-iso-translate \
     -quiet -cache-inodes -d -D -V "compress" miscdirs
 if [ "$?" != "0" ] ; then
-	echo "FAILURE: mkisofs of solarismisc failed"
+	print -u2 "$0: FAILURE: mkisofs of solarismisc failed"
 	exit 1	
 fi
 /bin/rm -rf miscdirs
 
-echo "Compressing misc filesystem image"
+print "Compressing misc filesystem image"
 LD_LIBRARY_PATH=${PKG_IMG_PATH}/usr/lib time ${PKG_IMG_PATH}/usr/sbin/lofiadm -C $COMPRESSION_TYPE ${PKG_IMG_PATH}/solarismisc.zlib >/dev/null 2>&1
 if [ "$?" != "0" ] ; then
-	echo "FAILURE: compression of solarismisc failed"
+	print -u2 "$0: FAILURE: compression of solarismisc failed"
 	exit 1	
 fi
 
